### ISSUE TITLE
Dodge in scatter,lines

### ISSUE THREAD

**Issue by behinger** [MakieOrg/AlgebraOfGraphics.jl#393] opened 2022-05-20 08:24 UTC
## Problem description
I often encountered the issue, that there is no way to dodge datapoints in a scatter (or less important imho line) plot.

That is going from here:
![image](https://user-images.githubusercontent.com/10183650/169485886-1d077c03-143c-49d7-b5d1-49928bf42ae9.png)
To here: 
![image](https://user-images.githubusercontent.com/10183650/169485997-2e050242-69a6-47b9-ad90-f5cfe590966c.png)

Something similar is asked here #230 I think

## Proposed solution
I dont understand enough of the internals, but as I understand Makie.jl implements the dodge feature for violin & histograms.

In ggplot2 dodging is possible by specifing a position-function (`position = position_dodge(width=0.2)`). I was expecting something like
`data(df) * mapping(x,y,color="categoryA",dodge="categoryA")  * visual(Scatter)` to "just work", by doding the colored datapoints.

Let's just hope I missed something ;-)

**Comment by behinger** [comment] 2023-02-05 13:05
ok - I needed this again and couldnt find a solution. I implemented a new Makie Recipe `Dodge`, which allows you to do exactly this.

Please find the gist here: https://gist.github.com/behinger/8df41a3e051979a8e8ee0068f1aac6b8

I don't really know whether `@recipe Dodge` should be rather in `Makie.jl` @SimonDanisch what do you think?

I also dont know if this is the nicest way, but one can dodge all kinds of plots. tried with scatter and errorbars. dodging in y instead of x is supported as well.
![image](https://user-images.githubusercontent.com/10183650/216820283-146f36f0-e58a-4c5b-8bef-c5fbf7fa0ec3.png)

MWE
```julia
begin
	using Makie
	using CairoMakie
	using HTTP
HTTP.download("https://gist.githubusercontent.com/behinger/8df41a3e051979a8e8ee0068f1aac6b8/raw/4c6f44603d4432b19c8abe2955eab4962a8ae45f/MakieDodge.jl",tempdir()) |>include
	
	#----
	x = [1,2,3,  1,2,3.,  3,2,1]
	y = [1.1,1.9,2.8,1,2,3,3.05,2.05,1.05]
	c = ["red","red","red","green","green","green","blue","blue","blue"]
	low,high = repeat([0.2],length(x))
	dodge(x,y,low,high;plot_fun=errorbars!,color=c)
	
	dodge!(x,y;color=c, plot_fun=scatter!)
	current_figure()
	

end
```

**Comment by behinger** [comment] 2023-02-05 13:06
ah and of course with AoG
![image](https://user-images.githubusercontent.com/10183650/216820584-df9a12f6-f4ca-470a-9fe3-6c103c2c4e99.png)

```julia
let
		d = DataFrame(:x=>["x2","x1","x2","x1","x3","x3","x4"],:y=>[2.,1.1,2.1,1.,3.,3.1,4],:c=>["a","a","b","b","b","b","b"])
	d.high = repeat([0.1],nrow(d))
	d.low = repeat([0.1],nrow(d))
	
	data(d)* 
		mapping(color=:c,dodge=:c) *
		(
			mapping(:x,:y,:low,:high,)* visual(Dodge,plot_fun=errorbars!) +
	 		mapping(:x,:y)			  * visual(Dodge)
		) |> draw
	
end
```

**Comment by pdeffebach** [comment] 2024-07-22 16:38
@jkrumbiegel I would be super interested in this feature! Not sure how to add it. But if it could go higher on the priority list I would appreciate it!

**Comment by jkrumbiegel** [comment] 2024-07-22 17:33
I'm not sure, yet, either, how exactly this could be implemented. But in principle one can add arbitrary keywords to the aesthetic mapping of a plotting function, which just have to be removed before everything is transferred to Makie. Maybe one could add some sort of generic logic to `to_entry` which detects the `dodge` keyword and modifies the data belonging to the `X` or `Y` aesthetic accordingly. The generic `to_entry` functions are here https://github.com/MakieOrg/AlgebraOfGraphics.jl/blob/a61e36191dc0939d33899c01764092203f6deccf/src/algebra/layers.jl#L314-L351. Then the plotting functions wouldn't need to know about dodging at all, they would just receive modified x and y data.

**Comment by pdeffebach** [comment] 2024-07-22 17:45
I think the issue is that Makie itself has no concept of dodge for certain things like lines and errorbars. So this has to be fixed upstream, right?

**Comment by jkrumbiegel** [comment] 2024-07-22 18:07
Well as I wrote above, if you consider dodging in data space, then you don't really have to add it to plotting functions. You could, but you don't have to, depending on what exactly is plotted and whether there's some advanced interactions like in barplots where width needs to change as well.

**Comment by pdeffebach** [comment] 2024-07-22 19:44
Yes sorry, my particular application is bar plots with error bars on the top.

**Comment by pdeffebach** [comment] 2024-07-23 14:32
As a concrete example, here is what I want to be able to do with AoG:

```
julia> df = DataFrame(
           g = ["a", "b", "c", "a", "b", "c"],  
           country = ["X", "X", "X", "Y", "Y", "Y"],
           val = [1.0, 1.5, 2.0, 4.3, 3.6, 2.9], 
           err = [0.2, 0.4, 0.1, 0.3, 0.1, 0.4]);

julia> data(df) * (mapping(:g, :val, color = :country, dodge = :country) * visual(BarPlot) + mapping(:g, :val, :err; dodge = :country) * visual(Errorbars)) |> draw
```

I get 

```
ERROR: ArgumentError: ProcessedLayer with plot type Plot{Makie.errorbars} did not have :dodge in its AestheticMapping. The mapping was {1 = AlgebraOfGraphics.AesX, 2 = AlgebraOfGraphics.AesY, 3 = AlgebraOfGraphics.AesDeltaY, :color = AlgebraOfGraphics.AesColor}
```

**Closed** 2024-09-17 10:25 UTC
