### ISSUE TITLE
Change `mapping` keyword from `col` to `column`

### ISSUE THREAD

**Issue by CameronBieganek** [MakieOrg/AlgebraOfGraphics.jl#405] opened 2022-06-15 13:43 UTC
I frequently misread the `col` keyword argument to `mapping` as "color". In the context of plotting, `"col" = "color"` springs to mind much more readily than `"col" = "column"`. In addition, R plots use the `col` keyword for "color":

https://bookdown.org/rdpeng/exdata/plotting-and-color-in-r.html

So anyone coming from R is likely to be confused.

**Comment by jkrumbiegel** [comment] 2024-08-22 18:13
I'm sympathetic to the cause, but I don't think it's worth the breaking change at this point, so I'm going to close this as not planned

**Closed by jkrumbiegel** 2024-08-22 18:13 UTC
